# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ dev_py_wheels ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
        python-version: ${{ matrix.python-version }}

    - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.11.2

    - name: Build wheels
      run: python3 -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD: ${{ matrix.cibuildwheel_python }}
        CIBW_BUILD_VERBOSITY: 1

    - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
        python-version: ${{ matrix.python-version }}

    - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.11.2

    - name: Build wheels
      run: python3 -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD: ${{ matrix.cibuildwheel_python }}
        CIBW_ARCHS_MACOS: x86_64 arm64
        CIBW_BUILD_VERBOSITY: 1

    - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
